export const CarrierSpoken: { [key in CarrierCode]: string } = {
  AAL: 'American',
  ACA: 'Air Canada',
  AFR: 'Air France',
  AIC: 'Air India',
  ASH: 'Air Shuttle',
  ASP: 'Airsprint',
  ASQ: 'Acey',
  BAW: 'Speed bird',
  BBA: 'Bombardier',
  BWA: 'Carribean',
  CJT: 'Cargojet',
  CMS: 'Access',
  CNK: 'Chinook',
  DAL: 'Delta',
  EGF: 'Eagleflight',
  EJA: 'Exec Jet',
  EJM: 'Jetspeed',
  ETD: 'Etihad',
  ETH: 'Ethiopian',
  FAB: 'First Air',
  FEX: 'Flight Exec',
  FJM: 'Green Heart',
  GLR: 'Glacier',
  JAL: 'Japan Air',
  JZA: 'Jazz',
  KBA: 'Borekair',
  KEE: 'Key stone',
  LXJ: 'Flex jet',
  MAL: 'Morning star',
  MPE: 'Empress',
  PAL: 'Phillipines',
  PDT: 'Peedmont',
  PIA: 'Pakistan',
  POE: 'Porter',
  PUL: 'Pulse',
  ROU: 'Rouge',
  TGO: 'Transport',
  UAL: 'United',
  UPS: 'U P S',
  WEW: 'Westwynd',
  WJA: 'West jet',
};

export enum CarrierCode {
  AAL = 'AAL',
  ACA = 'ACA',
  AFR = 'AFR',
  AIC = 'AIC',
  ASH = 'ASH',
  ASP = 'ASP',
  ASQ = 'ASQ',
  BAW = 'BAW',
  BBA = 'BBA',
  BWA = 'BWA',
  CJT = 'CJT',
  CMS = 'CMS',
  CNK = 'CNK',
  DAL = 'DAL',
  EGF = 'EGF',
  EJA = 'EJA',
  EJM = 'EJM',
  ETD = 'ETD',
  ETH = 'ETH',
  FAB = 'FAB',
  FEX = 'FEX',
  FJM = 'FJM',
  GLR = 'GLR',
  JAL = 'JAL',
  JZA = 'JZA',
  KBA = 'KBA',
  KEE = 'KEE',
  LXJ = 'LXJ',
  MAL = 'MAL',
  MPE = 'MPE',
  PAL = 'PAL',
  PDT = 'PDT',
  PIA = 'PIA',
  POE = 'POE',
  PUL = 'PUL',
  ROU = 'ROU',
  TGO = 'TGO',
  UAL = 'UAL',
  UPS = 'UPS',
  WEW = 'WEW',
  WJA = 'WJA',
}
