export enum PhaserCustomEvents {
  PLANE_SELECTED = 'PLANE_SELECTED',
  WP_CLICKED = 'WP_CLICKED',
  ACID_CLICKED = 'ACID_CLICKED',
  ACID_RIGHT_CLICKED = 'ACID_RIGHT_CLICKED',
  ALTITUDE_SUBMENU_CLICKED = 'ALTITUDE_SUBMENU_CLICKED',
  HEADING_SUBMENU_CLICKED = 'HEADING_SUBMENU_CLICKED',
  SPEED_SUBMENU_CLICKED = 'HEADING_SUBMENU_CLICKED',
  PILOT_SPEECH = 'PILOT_SPEECH',
  RIGHT_CLICKED_RADAR_BG = 'RIGHT_CLICKED_BG',
  HANDOFF_BUTTON_CLICKED = 'HANDOFF_BUTTON_CLICKED',
  ACCEPT_HANDOFF_BUTTON_CLICKED = 'ACCEPT_HANDOFF_BUTTON_CLICKED',
  PTL_BUTTON_CLICKED = 'PTL_BUTTON_CLICKED',
  HIDE_PLANE_BUTTON_CLICKED = 'HIDE_PLANE_BUTTON_CLICKED',
}

export enum ReactCustomEvents {
  ACTIVE_ARR = 'ACTIVE_ARR',
  AIRBORNE_DEP = 'AIRBORNE_DEP',
  REFRESH = 'REFRESH',
  PAUSE = 'PAUSE',
  UNPAUSE = 'UNPAUSE',
}
