export enum PhaserCustomEvents {
  PLANE_SELECTED = 'PLANE_SELECTED',
  WP_CLICKED = 'WP_CLICKED',
  ALTITUDE_SUBMENU_CLICKED = 'ALTITUDE_SUBMENU_CLICKED',
  HEADING_SUBMENU_CLICKED = 'HEADING_SUBMENU_CLICKED',
  SPEED_SUBMENU_CLICKED = 'HEADING_SUBMENU_CLICKED',
  PILOT_SPEECH = 'PILOT_SPEECH',
}

export enum ReactCustomEvents {
  AIRBORNE = 'AIRBORNE',
  REFRESH = 'REFRESH',
}
