export enum SidName {
  DEDKI = 'DEDKI DEP',
  VERDO = 'VERDO DEP',
  KEPTA = 'KEPTA DEP',
  ANCOL = 'ANCOL DEP',
  BETES = 'BETES DEP',
  MIXUT = 'MIXUT DEP',
  RIGUS = 'RIGUS DEP',
  GOPUP = 'GOPUP DEP',
  SEDOG = 'SEDOG DEP',
  AVSEP = 'AVSEP DEP',
  IKLEN = 'IKLEN DEP',
  KISEP = 'KISEP DEP',
  URSAL = 'URSAL DEP',
  BOMET = 'BOMET DEP',
  MAVAN = 'MAVAN DEP',
  TEVAD = 'TEVAD DEP',
  DUSOM = 'DUSOM DEP',
  OAKVL = 'OAKVL DEP',
  PEMBA = 'PEMBA DEP',
  PERLO = 'PERLO DEP',
  TULEK = 'TULEK DEP',
  LAKES = 'LAKES DEP',
  EBKIN = 'EBKIN DEP',
  MATES = 'MATES DEP',
  NOSIK = 'NOSIK DEP',
  NUGOP = 'NUGOP DEP',
}

export enum SatelliteName {
  YHM_ARR_MUXIG = 'YHM_ARR_MUXIG',
  YHM_ARR_UDMIK = 'YHM_ARR_UDMIK',
  YHM_DEP_TESUK = 'YHM_DEP_TESUK', // 33s
  YHM_DEP_UKPAG = 'YHM_DEP_UKPAG', // 33s
  YKF_DEP_DAVSI = 'YKF_DEP_DAVSI', // prop
  YKF_DEP_SANIN = 'YKF_DEP_SANIN', // jet
  YKZ_ARR = 'YKZ_ARR', // 06s
  YKZ_DEP_ANCOL = 'YKZ_DEP_ANCOL',
  YKZ_DEP_BETES = 'YKZ_DEP_BETES',
  YKZ_DEP_GOPUP = 'YKZ_DEP_GOPUP',
  YKZ_DEP_KEPTA = 'YKZ_DEP_KEPTA',
  YKZ_DEP_RIGUS = 'YKZ_DEP_RIGUS',
  YKZ_DEP_SEDOG = 'YKZ_DEP_SEDOG',
  YKZ_DEP_TONNY = 'YKZ_DEP_TONNY',
  YOO_ARR = 'YOO_ARR',
  YPQ_ARR = 'YPQ_ARR',
  YTZ_DEP_DAVSI = 'YTZ_DEP_DAVSI',
  YTZ_DEP_IKLEN = 'YTZ_DEP_IKLEN',
  YTZ_DEP_MAVAN = 'YTZ_DEP_MAVAN',
  YTZ_DEP_PERLO = 'YTZ_DEP_PERLO',
  YTZ_DEP_TEVAD = 'YTZ_DEP_TEVAD',
  YZD_DEP_SEDOG = 'YZD_DEP_SEDOG',
}
