import { WaypointDataDep15s } from '../../types/WaypointTypesDep';
import { SidName } from '../../types/SidAndSatelliteTypes';
import { WP_DICT_Rwy15s_DEP } from '../WaypointConfigDep/WaypointConfigDep15s';

export const SID_ROUTES_15s: {
  [key in SidName]: WaypointDataDep15s[];
} = {
  'ANCOL DEP': [WP_DICT_Rwy15s_DEP.MIXUT, WP_DICT_Rwy15s_DEP.LETOR],
  'AVSEP DEP': [
    WP_DICT_Rwy15s_DEP.BOVAL,
    WP_DICT_Rwy15s_DEP.VIBNA,
    WP_DICT_Rwy15s_DEP.IPSOT,
    WP_DICT_Rwy15s_DEP.URSAL,
    WP_DICT_Rwy15s_DEP.NUGOP,
  ],
  'BETES DEP': [WP_DICT_Rwy15s_DEP.OAKVL, WP_DICT_Rwy15s_DEP.BETES],
  'BOMET DEP': [WP_DICT_Rwy15s_DEP.DAVSI, WP_DICT_Rwy15s_DEP.TESUK],
  'DEDKI DEP': [
    WP_DICT_Rwy15s_DEP.ALKUT,
    WP_DICT_Rwy15s_DEP.KODAL,
    WP_DICT_Rwy15s_DEP.DEDKI,
  ],
  'DUSOM DEP': [WP_DICT_Rwy15s_DEP.DUSOM, WP_DICT_Rwy15s_DEP.RIGUS],
  'EBKIN DEP': [
    WP_DICT_Rwy15s_DEP.ETLER,
    WP_DICT_Rwy15s_DEP.EBKIN,
    WP_DICT_Rwy15s_DEP.KISEP,
  ],
  'GOPUP DEP': [
    WP_DICT_Rwy15s_DEP.BOVAL,
    WP_DICT_Rwy15s_DEP.VIBNA,
    WP_DICT_Rwy15s_DEP.IPSOT,
    WP_DICT_Rwy15s_DEP.TULEK,
  ],
  'IKLEN DEP': [
    WP_DICT_Rwy15s_DEP.BORUX,
    WP_DICT_Rwy15s_DEP.ETLER,
    WP_DICT_Rwy15s_DEP.IKLEN,
    WP_DICT_Rwy15s_DEP.TONNY,
  ],
  'KEPTA DEP': [WP_DICT_Rwy15s_DEP.RIKEM, WP_DICT_Rwy15s_DEP.KEPTA],
  'KISEP DEP': [
    WP_DICT_Rwy15s_DEP.BORUX,
    WP_DICT_Rwy15s_DEP.ETLER,
    WP_DICT_Rwy15s_DEP.EBKIN,
    WP_DICT_Rwy15s_DEP.KISEP,
  ],
  'LAKES DEP': [
    WP_DICT_Rwy15s_DEP.ETLER,
    WP_DICT_Rwy15s_DEP.SEDOG,
    WP_DICT_Rwy15s_DEP.TANGI,
  ],
  'MATES DEP': [
    WP_DICT_Rwy15s_DEP.ETLER,
    WP_DICT_Rwy15s_DEP.IKLEN,
    WP_DICT_Rwy15s_DEP.TONNY,
  ],
  'MAVAN DEP': [WP_DICT_Rwy15s_DEP.RIKEM, WP_DICT_Rwy15s_DEP.KEPTA],
  'MIXUT DEP': [WP_DICT_Rwy15s_DEP.MIXUT, WP_DICT_Rwy15s_DEP.LETOR],
  'NOSIK DEP': [
    WP_DICT_Rwy15s_DEP.IPSOT,
    WP_DICT_Rwy15s_DEP.URSAL,
    WP_DICT_Rwy15s_DEP.NOSIK,
  ],
  'NUGOP DEP': [
    WP_DICT_Rwy15s_DEP.IPSOT,
    WP_DICT_Rwy15s_DEP.URSAL,
    WP_DICT_Rwy15s_DEP.NUGOP,
  ],
  'OAKVL DEP': [WP_DICT_Rwy15s_DEP.OAKVL, WP_DICT_Rwy15s_DEP.BETES],
  'PEMBA DEP': [WP_DICT_Rwy15s_DEP.MIXUT, WP_DICT_Rwy15s_DEP.LETOR],
  'PERLO DEP': [WP_DICT_Rwy15s_DEP.MIXUT, WP_DICT_Rwy15s_DEP.LETOR],
  'RIGUS DEP': [WP_DICT_Rwy15s_DEP.DUSOM, WP_DICT_Rwy15s_DEP.RIGUS],
  'SEDOG DEP': [WP_DICT_Rwy15s_DEP.SEDOG, WP_DICT_Rwy15s_DEP.TANGI],
  'TEVAD DEP': [WP_DICT_Rwy15s_DEP.NADUM, WP_DICT_Rwy15s_DEP.TEVAD],
  'TULEK DEP': [WP_DICT_Rwy15s_DEP.IPSOT, WP_DICT_Rwy15s_DEP.TULEK],
  'URSAL DEP': [
    WP_DICT_Rwy15s_DEP.BOVAL,
    WP_DICT_Rwy15s_DEP.VIBNA,
    WP_DICT_Rwy15s_DEP.IPSOT,
    WP_DICT_Rwy15s_DEP.URSAL,
    WP_DICT_Rwy15s_DEP.NOSIK,
  ],
  'VERDO DEP': [
    WP_DICT_Rwy15s_DEP.ALKUT,
    WP_DICT_Rwy15s_DEP.PUTON,
    WP_DICT_Rwy15s_DEP.VERDO,
  ],
};
