import { WaypointDataDepCommon } from '../../types/WaypointTypesDep';
import { SatelliteName } from '../../types/SidAndSatelliteTypes';
import { WP_DICT_DEP_COMMON } from '../WaypointConfigDep/WaypointConfigDepCommon';

export const SATELLITE_ROUTES: {
  [key in SatelliteName]: WaypointDataDepCommon[];
} = {
  YHM_ARR_MUXIG: [
    WP_DICT_DEP_COMMON.ILUSI,
    WP_DICT_DEP_COMMON.YYZ,
    WP_DICT_DEP_COMMON.MUXIG,
    WP_DICT_DEP_COMMON.BIMTI,
    WP_DICT_DEP_COMMON.SAXIL,
    WP_DICT_DEP_COMMON.YHM,
  ],
  YHM_ARR_UDMIK: [
    WP_DICT_DEP_COMMON.ILUSI,
    WP_DICT_DEP_COMMON.YYZ,
    WP_DICT_DEP_COMMON.UDMIK,
    WP_DICT_DEP_COMMON.BIMTI,
    WP_DICT_DEP_COMMON.SAXIL,
    WP_DICT_DEP_COMMON.YHM,
  ],
  YHM_DEP_TESUK: [WP_DICT_DEP_COMMON.TESUK],
  YHM_DEP_UKPAG: [WP_DICT_DEP_COMMON.UKPAG],
  YKF_DEP_DAVSI: [
    WP_DICT_DEP_COMMON.YKF,
    WP_DICT_DEP_COMMON.YWT,
    WP_DICT_DEP_COMMON.ROKTO,
    WP_DICT_DEP_COMMON.YYZ,
    WP_DICT_DEP_COMMON.DAVSI,
    WP_DICT_DEP_COMMON.TESUK,
  ],
  YKF_DEP_SANIN: [
    WP_DICT_DEP_COMMON.YKF,
    WP_DICT_DEP_COMMON.YWT,
    WP_DICT_DEP_COMMON.ROKTO,
    WP_DICT_DEP_COMMON.YYZ,
    WP_DICT_DEP_COMMON.SANIN,
  ],
  YKZ_ARR: [WP_DICT_DEP_COMMON.YKF, WP_DICT_DEP_COMMON.YKZ],
  YKZ_DEP_ANCOL: [WP_DICT_DEP_COMMON.ANCOL, WP_DICT_DEP_COMMON.LETOR],
  YKZ_DEP_BETES: [WP_DICT_DEP_COMMON.OAKVL, WP_DICT_DEP_COMMON.BETES],
  YKZ_DEP_GOPUP: [WP_DICT_DEP_COMMON.TULEK],
  YKZ_DEP_RIGUS: [WP_DICT_DEP_COMMON.DUSOM],
  YKZ_DEP_KEPTA: [WP_DICT_DEP_COMMON.RIKEM, WP_DICT_DEP_COMMON.KEPTA],
  YKZ_DEP_TONNY: [WP_DICT_DEP_COMMON.TONNY],
  YKZ_DEP_SEDOG: [WP_DICT_DEP_COMMON.SEDOG, WP_DICT_DEP_COMMON.TANGI],
  YOO_ARR: [
    WP_DICT_DEP_COMMON.YWT,
    WP_DICT_DEP_COMMON.ROKTO,
    WP_DICT_DEP_COMMON.YYZ,
    WP_DICT_DEP_COMMON.OO,
  ],
  YPQ_ARR: [
    WP_DICT_DEP_COMMON.YWT,
    WP_DICT_DEP_COMMON.ROKTO,
    WP_DICT_DEP_COMMON.DAVSI,
    WP_DICT_DEP_COMMON.TALEB,
  ],
  YTZ_DEP_DAVSI: [WP_DICT_DEP_COMMON.DAVSI, WP_DICT_DEP_COMMON.TESUK],
  YTZ_DEP_IKLEN: [WP_DICT_DEP_COMMON.IKLEN, WP_DICT_DEP_COMMON.TONNY],
  YTZ_DEP_MAVAN: [WP_DICT_DEP_COMMON.RIKEM, WP_DICT_DEP_COMMON.KEPTA],
  YTZ_DEP_PERLO: [WP_DICT_DEP_COMMON.ANCOL, WP_DICT_DEP_COMMON.LETOR],
  YTZ_DEP_TEVAD: [WP_DICT_DEP_COMMON.NADUM, WP_DICT_DEP_COMMON.TEVAD],
  YZD_DEP_SEDOG: [WP_DICT_DEP_COMMON.SEDOG, WP_DICT_DEP_COMMON.TANGI],
};
