import { WaypointDataDep24s } from '../../types/WaypointTypesDep';
import { SidName } from '../../types/SidAndSatelliteTypes';
import { WP_DICT_DEP_24s } from '../WaypointConfigDep/WaypointConfigDep24s';

export const SID_ROUTES_24s: {
  [key in SidName]: WaypointDataDep24s[];
} = {
  'ANCOL DEP': [WP_DICT_DEP_24s.MIXUT, WP_DICT_DEP_24s.LETOR],
  'AVSEP DEP': [
    WP_DICT_DEP_24s.TILAM,
    WP_DICT_DEP_24s.AVSEP,
    WP_DICT_DEP_24s.NUGOP,
  ],
  'BETES DEP': [
    WP_DICT_DEP_24s.MURNO,
    WP_DICT_DEP_24s.OAKVL,
    WP_DICT_DEP_24s.BETES,
  ],
  'BOMET DEP': [
    WP_DICT_DEP_24s.MAVAN,
    WP_DICT_DEP_24s.GAGPO,
    WP_DICT_DEP_24s.DAVSI,
    WP_DICT_DEP_24s.TESUK,
  ],
  'DEDKI DEP': [
    WP_DICT_DEP_24s.SAVUR,
    WP_DICT_DEP_24s.SEKIT,
    WP_DICT_DEP_24s.DEDKI,
  ],
  'DUSOM DEP': [
    WP_DICT_DEP_24s.SAVUR,
    WP_DICT_DEP_24s.DUSOM,
    WP_DICT_DEP_24s.RIGUS,
  ],
  'EBKIN DEP': [
    WP_DICT_DEP_24s.MATES,
    WP_DICT_DEP_24s.EBKIN,
    WP_DICT_DEP_24s.KISEP,
  ],
  'GOPUP DEP': [WP_DICT_DEP_24s.TILAM, WP_DICT_DEP_24s.TULEK],
  'IKLEN DEP': [
    WP_DICT_DEP_24s.BISTI,
    WP_DICT_DEP_24s.NAMGI,
    WP_DICT_DEP_24s.IKLEN,
    WP_DICT_DEP_24s.TONNY,
  ],
  'KEPTA DEP': [
    WP_DICT_DEP_24s.SAVUR,
    WP_DICT_DEP_24s.SEKIT,
    WP_DICT_DEP_24s.RIKEM,
    WP_DICT_DEP_24s.KEPTA,
  ],
  'KISEP DEP': [
    WP_DICT_DEP_24s.BISTI,
    WP_DICT_DEP_24s.NAMGI,
    WP_DICT_DEP_24s.EBKIN,
    WP_DICT_DEP_24s.KISEP,
  ],
  'LAKES DEP': [
    WP_DICT_DEP_24s.MATES,
    WP_DICT_DEP_24s.SEDOG,
    WP_DICT_DEP_24s.TANGI,
  ],
  'MATES DEP': [
    WP_DICT_DEP_24s.MATES,
    WP_DICT_DEP_24s.IKLEN,
    WP_DICT_DEP_24s.TONNY,
  ],
  'MAVAN DEP': [
    WP_DICT_DEP_24s.MAVAN,
    WP_DICT_DEP_24s.RIKEM,
    WP_DICT_DEP_24s.KEPTA,
  ],
  'MIXUT DEP': [WP_DICT_DEP_24s.MIXUT, WP_DICT_DEP_24s.LETOR],
  'NOSIK DEP': [WP_DICT_DEP_24s.URSAL, WP_DICT_DEP_24s.NOSIK],
  'NUGOP DEP': [WP_DICT_DEP_24s.AVSEP, WP_DICT_DEP_24s.NUGOP],
  'OAKVL DEP': [
    WP_DICT_DEP_24s.SAVUR,
    WP_DICT_DEP_24s.OAKVL,
    WP_DICT_DEP_24s.BETES,
  ],
  'PEMBA DEP': [
    WP_DICT_DEP_24s.TILAM,
    WP_DICT_DEP_24s.MIXUT,
    WP_DICT_DEP_24s.LETOR,
  ],
  'PERLO DEP': [
    WP_DICT_DEP_24s.TILAM,
    WP_DICT_DEP_24s.MIXUT,
    WP_DICT_DEP_24s.LETOR,
  ],
  'RIGUS DEP': [
    WP_DICT_DEP_24s.MURNO,
    WP_DICT_DEP_24s.DUSOM,
    WP_DICT_DEP_24s.RIGUS,
  ],
  'SEDOG DEP': [
    WP_DICT_DEP_24s.BISTI,
    WP_DICT_DEP_24s.NAMGI,
    WP_DICT_DEP_24s.SEDOG,
    WP_DICT_DEP_24s.TANGI,
  ],
  'TEVAD DEP': [
    WP_DICT_DEP_24s.MAVAN,
    WP_DICT_DEP_24s.NADUM,
    WP_DICT_DEP_24s.TEVAD,
  ],
  'TULEK DEP': [WP_DICT_DEP_24s.TULEK],
  'URSAL DEP': [
    WP_DICT_DEP_24s.TILAM,
    WP_DICT_DEP_24s.URSAL,
    WP_DICT_DEP_24s.NOSIK,
  ],
  'VERDO DEP': [
    WP_DICT_DEP_24s.SAVUR,
    WP_DICT_DEP_24s.SEKIT,
    WP_DICT_DEP_24s.VERDO,
  ],
};
