import { WP_DICT_DEP_06s } from '../WaypointConfigDep/WaypointConfigDep06s';
import { WaypointDataDep06s } from '../../types/WaypointTypesDep';
import { SidName } from '../../types/SidAndSatelliteTypes';

export const SID_ROUTES_06s: {
  [key in SidName]: WaypointDataDep06s[];
} = {
  'ANCOL DEP': [
    WP_DICT_DEP_06s.MOBEL,
    WP_DICT_DEP_06s.BIRLI,
    WP_DICT_DEP_06s.VIDRA,
    WP_DICT_DEP_06s.ANCOL,
    WP_DICT_DEP_06s.LETOR,
  ],
  'AVSEP DEP': [
    WP_DICT_DEP_06s.KEDSI,
    WP_DICT_DEP_06s.DUVKO,
    WP_DICT_DEP_06s.AVSEP,
    WP_DICT_DEP_06s.NUGOP,
  ],
  'BETES DEP': [
    WP_DICT_DEP_06s.MOBEL,
    WP_DICT_DEP_06s.BIRLI,
    WP_DICT_DEP_06s.VIDRA,
    WP_DICT_DEP_06s.OAKVL,
    WP_DICT_DEP_06s.BETES,
  ],
  'BOMET DEP': [WP_DICT_DEP_06s.AVROS, WP_DICT_DEP_06s.TESUK],
  'DEDKI DEP': [
    WP_DICT_DEP_06s.ALKUT,
    WP_DICT_DEP_06s.KODAL,
    WP_DICT_DEP_06s.DEDKI,
  ],
  'DUSOM DEP': [
    WP_DICT_DEP_06s.PERLO,
    WP_DICT_DEP_06s.OMAPA,
    WP_DICT_DEP_06s.DUSOM,
    WP_DICT_DEP_06s.RIGUS,
  ],
  'EBKIN DEP': [WP_DICT_DEP_06s.EBKIN, WP_DICT_DEP_06s.KISEP],
  'GOPUP DEP': [
    WP_DICT_DEP_06s.KEDSI,
    WP_DICT_DEP_06s.DUVKO,
    WP_DICT_DEP_06s.TULEK,
  ],
  'IKLEN DEP': [
    WP_DICT_DEP_06s.GOTIM,
    WP_DICT_DEP_06s.IKLEN,
    WP_DICT_DEP_06s.TONNY,
  ],
  'KEPTA DEP': [
    WP_DICT_DEP_06s.MOBEL,
    WP_DICT_DEP_06s.RIKEM,
    WP_DICT_DEP_06s.KEPTA,
  ],
  'KISEP DEP': [
    WP_DICT_DEP_06s.GOTIM,
    WP_DICT_DEP_06s.EBKIN,
    WP_DICT_DEP_06s.KISEP,
  ],
  'LAKES DEP': [WP_DICT_DEP_06s.SEDOG, WP_DICT_DEP_06s.TANGI],
  'MATES DEP': [WP_DICT_DEP_06s.IKLEN, WP_DICT_DEP_06s.TONNY],
  'MAVAN DEP': [
    WP_DICT_DEP_06s.PERLO,
    WP_DICT_DEP_06s.RIKEM,
    WP_DICT_DEP_06s.KEPTA,
  ],
  'MIXUT DEP': [
    WP_DICT_DEP_06s.MOBEL,
    WP_DICT_DEP_06s.BIRLI,
    WP_DICT_DEP_06s.VIDRA,
    WP_DICT_DEP_06s.ANCOL,
    WP_DICT_DEP_06s.LETOR,
  ],
  'NOSIK DEP': [
    WP_DICT_DEP_06s.MEMPA,
    WP_DICT_DEP_06s.SIDVU,
    WP_DICT_DEP_06s.URSAL,
    WP_DICT_DEP_06s.NOSIK,
  ],
  'NUGOP DEP': [
    WP_DICT_DEP_06s.MEMPA,
    WP_DICT_DEP_06s.SIDVU,
    WP_DICT_DEP_06s.AVSEP,
    WP_DICT_DEP_06s.NUGOP,
  ],
  'OAKVL DEP': [
    WP_DICT_DEP_06s.PERLO,
    WP_DICT_DEP_06s.OMAPA,
    WP_DICT_DEP_06s.OAKVL,
    WP_DICT_DEP_06s.BETES,
  ],
  'PEMBA DEP': [
    WP_DICT_DEP_06s.PERLO,
    WP_DICT_DEP_06s.OMAPA,
    WP_DICT_DEP_06s.ANCOL,
    WP_DICT_DEP_06s.LETOR,
  ],
  'PERLO DEP': [
    WP_DICT_DEP_06s.PERLO,
    WP_DICT_DEP_06s.OMAPA,
    WP_DICT_DEP_06s.ANCOL,
    WP_DICT_DEP_06s.LETOR,
  ],
  'RIGUS DEP': [
    WP_DICT_DEP_06s.MOBEL,
    WP_DICT_DEP_06s.BIRLI,
    WP_DICT_DEP_06s.VIDRA,
    WP_DICT_DEP_06s.DUSOM,
    WP_DICT_DEP_06s.RIGUS,
  ],
  'SEDOG DEP': [
    WP_DICT_DEP_06s.GOTIM,
    WP_DICT_DEP_06s.SEDOG,
    WP_DICT_DEP_06s.TANGI,
  ],
  'TEVAD DEP': [
    WP_DICT_DEP_06s.PERLO,
    WP_DICT_DEP_06s.NADUM,
    WP_DICT_DEP_06s.TEVAD,
  ],
  'TULEK DEP': [
    WP_DICT_DEP_06s.MEMPA,
    WP_DICT_DEP_06s.SIDVU,
    WP_DICT_DEP_06s.TULEK,
  ],
  'URSAL DEP': [
    WP_DICT_DEP_06s.KEDSI,
    WP_DICT_DEP_06s.DUVKO,
    WP_DICT_DEP_06s.URSAL,
    WP_DICT_DEP_06s.NOSIK,
  ],
  'VERDO DEP': [
    WP_DICT_DEP_06s.ALKUT,
    WP_DICT_DEP_06s.PUTON,
    WP_DICT_DEP_06s.VERDO,
  ],
};
